#!/bin/sh
unset NODE_OPTIONS
ELECTRON_RUN_AS_NODE=1 "/usr/lib/code-server/lib/node" "/home/user/.local/share/code-server/User/globalStorage/github.copilot-chat/debugCommand/copilotDebugCommand.js" "code-oss://github.copilot-chat" "code --openExternal " "$@"